# Generated by Django 2.2 on 2021-03-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('nik', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=30)),
                ('no_telpon', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=20)),
                ('jenis_surat', models.CharField(choices=[(1, 'Keluhan'), (2, 'Pendafataran KTP'), (3, 'Legalisir'), (4, 'Keterangan Tidak Mampu')], default=1, max_length=40)),
                ('keterangan_tambahan', models.TextField(max_length=150)),
            ],
        ),
    ]
