# Generated by Django 2.2 on 2021-03-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suket', '0003_auto_20210309_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borang',
            name='jenis_surat',
            field=models.CharField(choices=[('Keluhan', 'Keluhan'), ('Daftar KTP', 'Pendafataran KTP'), ('Legalisir', 'Legalisir'), ('KTM', 'Keterangan Tidak Mampu')], default='Pilih Jenis Surat', max_length=40),
        ),
    ]
